import React from 'react';

import { WebtauThemeSwitcher } from './WebtauThemeSwitcher';
import Report from '../Report';

import './WebtauPoweredBy.css';

interface Props {
  report: Report;
}

export function WebtauPoweredBy({ report }: Props) {
  return (
    <div className="webtau-summary-generated-by-and-theme-panel">
      <div className="webtau-generated-by">
        generated by
        <a href="https://github.com/testingisdocumenting/webtau" target="_blank" rel="noopener noreferrer">
          {'webtau ' + report.version}
        </a>
      </div>
      <WebtauThemeSwitcher />
    </div>
  );
}
