import React from 'react';

import { WebTauThemeSwitcher } from './WebTauThemeSwitcher';
import Report from '../Report';

import './WebTauPoweredBy.css';

interface Props {
  report: Report;
}

export function WebTauPoweredBy({ report }: Props) {
  return (
    <div className="webtau-summary-generated-by-and-theme-panel">
      <div className="webtau-generated-by">
        <span>generated by</span>
        <a href="https://github.com/testingisdocumenting/webtau" target="_blank" rel="noopener noreferrer">
          {'webtau ' + report.version}
        </a>
      </div>
      <WebTauThemeSwitcher />
    </div>
  );
}
