name: Build webtau

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [1.8,  11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Set up grahpviz
        run: sudo apt-get install graphviz

      - name: Build with xvfb enabled
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: mvn -B verify

      - uses: actions/upload-artifact@v2
        with:
          name: report-testing-report
          path: webtau-report-testing/src/test/groovy/webtau.report.html

      - uses: actions/upload-artifact@v2
        with:
          name: features-testing
          path: webtau-feature-testing/**/webtau*.report.html
