name: Build webtau

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [1.8,  11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Set up grahpviz
        run: sudo apt-get install graphviz

      - name: Build with xvfb enabled
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: mvn -B verify

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          if: always()
          name: failed-webtau-reports
          path: "*/**/*.html"
          retention-days: 3
